Added autosklearn model and notebook
rawan-a-d/Air-Quality-Prediction pull request #18
Opened 2022-12-22 10:22 UTC by Stefan415849

2022-12-24 13:03 UTC, rawan-a-d requested changes
See comments

2023-01-10 12:12 UTC, Stefan415849 commented
<p>The numerical and categorical columns are divided for the purpose of training.</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-01-10 13:59 UTC, Ranim1996 approved these changes

2023-01-10 13:59 UTC, rawan-a-d approved these changes

2023-01-10 14:03 UTC, rawan-a-d requested changes
There are comments in notebook

2023-01-10 14:04 UTC, Ranim1996 requested changes
Check the notebook.ipynb there is an error, fix it :)

2023-01-11 11:06 UTC, jarnovdh15 commented
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-01-11 11:07 UTC, jarnovdh15 commented
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-01-11 11:18 UTC, jarnovdh15 commented
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-01-11 19:43 UTC, rawan-a-d commented
<p>I still see it</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-01-12 11:31 UTC, jarnovdh15 approved these changes

2023-01-12 11:32 UTC, closed without merging

2023-01-12 11:44 UTC, Ranim1996 commented on notebook.ipynb
>      "from datetime import datetime, date, timedelta\n",
<p>There is an error here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/18/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='304'/>