Air pollution branch
rawan-a-d/Air-Quality-Prediction pull request #3
Opened 2022-11-22 00:40 UTC by SpaceCadet5100

2022-11-22 12:43 UTC, rawan-a-d requested changes
This is not what I meant when I said you need to make the notebook shorter.
Separating the notebook into three is not a fix because we need to combine everything in the development branch so the problem will be moved there.

So in air_pollution.ipynb, select a few rows (5 to 10) of the dataframe
![image](https://user-images.githubusercontent.com/27498593/203316578-e5d7a248-3725-4e21-b633-9a20cb351eb8.png)

2022-11-22 12:43 UTC, Ranim1996 requested changes
I think we agreed to get 5 to 10 max rows from the dataset you are working on to solve the problem.
We did not mean to separate the code into files to fix the issue.

Keeping the code as it is will affect the dev branch and cause the same problem when you merge it.

2022-11-22 17:20 UTC, jarnovdh15 commented on air_pollution.ipynb
> +    "<h4><font color=brown>Average PM2.5 per day</font></h4>"
the table of content doesn't show anything for me

2022-11-22 17:20 UTC, jarnovdh15 commented on air_pollution.ipynb
> +    "<h4><font color=brown>Average PM2.5 per day</font></h4>"
![image](https://user-images.githubusercontent.com/118273022/203379993-ebc5ec06-38ec-419b-83fc-6b1f47f41b12.png)

2022-11-22 17:24 UTC, jarnovdh15 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Maybe use the same postal codes and dates for the data

2022-11-22 18:13 UTC, rawan-a-d requested changes

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown>Reading the dataset from the system</font></h4>"
We should use the same style.
Write this instead:
`<h3><font color=steelblue>Pollution dataset </font></h3>`

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown>Getting the basic information about the dataset</font></h4>"
This should be:
`<h4><font color=mediumvioletred>Read CSV files </font></h4>`

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +   "source": [
Add an "h4" heading here as well

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "df_ap.info()\n",
Separate these lines into two cells

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "plt.show()\n",
Add a semicolon at the end

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown>Testing for Normality</font></h4>"
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "#The distribution of the PM2.5 data has a short head and a long tail\n",
You can add the conclusion after the graphs as a text cell

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown>Correlations in the dataset</font></h4>"
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown>Average PM2.5 per day</font></h4>"
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "df_ap_day_mean = df_ap.groupby(pd.Grouper(freq='D', key='date')).mean()\n",
These two graphs are empty
![image](https://user-images.githubusercontent.com/27498593/203383073-fb5ac005-8194-47f3-b530-ab830e0392e0.png)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown> Worst sum total pollution in different postal code areas</font></h4>"
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +   "source": [
Separate the table from the graph

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "<h4><font color=brown> Most peak pollution in different postal code areas</font></h4>"
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Separate the table from the graph

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
You can add the conclusion after the graph as a text cell

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
You have a typo (pollution)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "Most populted areas with the polution type:\n"
You have typos (pollution, populated)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +   "source": [
I think this should be a bar chart since different zipcodes have nothing to do with each other

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "df_ap_sp = df_ap.groupby(['PC4']).sum(numeric_only=True)\n",
To measure the pollution of pm2.5 and pm10 specifically you need to take the average per day not the sum.
I am not sure about the other pollutants.

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "df_ap_sp.plot(legend=True, figsize=(10,5), title=\"Sum total pollution in different postal code areas\")\n",
Add an xlabel, maybe Zipcode is clearer than PC4

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +    "print('Most populted areas with the polution type:')\n",
More typos (populated, pollution)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Use same style of h4 heading

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Separate the graph from the table

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Another typo (pollution)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Same feedback as previous graph (xlabel, mean instead of sum)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Use same style of h4 heading
You have a typo (polluted)

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
I don't understand the purpose of these graphs.
and why do average and the date have the same value?

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
polluted

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
I don't understand the purpose of these graphs.

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
On the xlabels I see some dates but not all and there's no time.
What is the most polluted area and why isn't it mentioned in the graph?

2022-11-22 18:13 UTC, rawan-a-d commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Can you share the source you used to determine these values?

2022-11-22 18:14 UTC, Ranim1996 requested changes

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +    "plt.show()\n",
what do you mean with testing for normality? I did not get the idea of the graph

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +    "<h4><font color=brown>Average PM2.5 per day</font></h4>"
Maybe you can separate the graphs in 2 different cells.
Why the first graph is empty and the second one is almost empty, maybe you can add comments describing the result you are getting.

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Maybe you can make use of a bar chart instead of a line. In this may it looks that there are continuous between the postcode for pollution.

Same goes to the previous 2 graphs

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Do you mean most 'Polluted' day per pollution type, per postal code(day mean)

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
I did not understand the graphs can you explain them, and why are the average day and date have the same values?

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
Typo "pluted"

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
I do not understand the aim/goal of these graphs as well.

2022-11-22 18:14 UTC, Ranim1996 commented on air_pollution.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAlAAAAFRCAYAAAC7VpN9AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAC9lUlEQVR4nOy
The title says pm2.5 per hour.
xlabel says date and hour.

The graph does not contain any hour/time.

2022-11-24 11:49 UTC, Ranim1996 approved these changes

2022-11-24 12:12 UTC, dennycox approved these changes

2022-11-24 12:15 UTC, jarnovdh15 approved these changes

2022-11-24 12:35 UTC, rawan-a-d approved these changes

2022-11-24 12:37 UTC, merged